import japan_text from '../autogenerated/texts'

class JALocalizable {
  constructor(hash = {}) {
    this.texts = Object.keys(hash).reduce((newHash, key) => {
      newHash[key.replace(/{JAPAN_ONLY}/, '')] = hash[key];
      return newHash;
    }, {});
  }

  localize(text, params) {
    const index = text.replace(/[\s|.]/g, '_');
    // only do templating when explicitly required
    const _text = this.texts[index] || text;
    return params ? this.template(_text, params) : _text;
  }

  template(string, content) {
    return string.replace(/\[_(\d+)\]/g, (s, index) => {
      return content[(Number(index)) - 1];
    });
  }
}

let local;
const text = (text, params) => {
  const lang = (typeof page === 'object' ? page.language() : 'JA');
  if (!local) {
    local = japan_text !== 'undefined' && lang === 'JA' ?
      new JALocalizable(japan_text.JA) :
      new JALocalizable();
  }

  return local.localize(text, params);
};

export default text;
